Teilt_Fahrrad/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView



urlpatterns = [
    path('admin/', admin.site.urls),
    #    path('', RedirectView.as_view(url='/accounts/login/')),
    #path('accounts/', include('accounts.urls')),
    path('', RedirectView.as_view(url='/accounts/login/')),
    path('accounts/', include("accounts.urls")),
    path('admin_func/', include("admin_func.urls")),
    path('bicycle_borrow_sub_sys/', include('bicycle_borrow_sub_sys.urls')),
]

accounts/urls.py
'''
Created on 2018/12/12

@author: t16cs060
'''

from django.urls import path
from . import views
from django.urls.conf import include

app_name = 'accounts'

urlpatterns = [
    path('login/', views.employee_login, name='login'),
    path('logout/', views.employee_logout, name='logout'),
    path('manager_login/', views.manager_login, name='manager_login'),
    path('manager_logout/', views.manager_logout, name='manager_logout'),
    path('top_test/', views.top_test, name='top_test'),
    path('manager_top_test/', views.manager_top_test, name='manager_top_test')
]

admin_func/urls.py
from django.urls import path
from . import views
from django.urls.conf import include

app_name = 'admin_func'

urlpatterns = [
    path('', views.top, name='top'),
    path('transfer_warning/<int:num>', views.transfer_warning, name='transfer_warning'),
    path('transfer_comp/<int:num>', views.transfer_comp, name='transfer_comp'),
]

bicycle_borrow_sub_sys/urls.py
from django.urls import path
from . import views
from django.urls.conf import include

app_name = 'bicycle_borrow_sub_sys'

urlpatterns = [
    path('', views.top, name='top'),
    path('borrow_bicycle/', views.borrow_bicycle, name='borrow_bicycle'),
    path('borrow_warning/<int:num>', views.borrow_warning, name='borrow_warning'),
    path('borrowed/<int:num>', views.borrowed, name='borrowed'),
    path('return_bicycle/', views.return_bicycle, name='return_bicycle'),
    path('return_warning/', views.return_warning, name='return_warning'),
    path('returned/<int:num>', views.returned, name='returned'),
    path('accounts/',include('accounts.urls'))
    ]

admin_func/models.py
from django.db import models
from accounts.models import Employee
from bicycle_borrow_sub_sys.models import Bicycle
from bicycle_borrow_sub_sys.models import Office
from bicycle_borrow_sub_sys.models import Borrow_history
# Create your models here.

admin_func/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .models import Borrow_history
from django.shortcuts import redirect
from .models import Bicycle
import datetime
import time
from .models import Office
from django.urls import reverse
from django.contrib import messages
from django.shortcuts import render
from django.http import HttpResponse
from .models import Borrow_history
from django.shortcuts import redirect
from .models import Bicycle
import datetime
from django.contrib.auth.decorators import login_required
import time
from django.urls import reverse
from django.contrib import messages
from datetime import datetime,timedelta
from .models import Employee

@login_required
def top(request):
    office2 = Office.objects.get(office_id=2)
    office1 = Office.objects.get(office_id=1)
    office3 = Office.objects.get(office_id=3)
    data = Borrow_history.objects.all().order_by('bicycle_id')
    alloffice = Office.objects.all().order_by('office_id')
    nums1 = Bicycle.objects.all().filter(office_id=1).count()
    nums2 = Bicycle.objects.all().filter(office_id=2).count()
    nums3 = Bicycle.objects.all().filter(office_id=3).count()
    params = {
        'title':'管理者用トップ画面',
        'msg':'移動する自転車を選択してください',
        #'form':borrow_bicycleForm(),
        'data':data,
        'nums1':nums1,
        'nums2':nums2,
        'nums3':nums3,
        'alloffice':alloffice,
        'office1':office1,
        'office2':office2,
        'office3':office3,
        }
    return render(request, 'admin_func/top.html', params)

@login_required
def transfer_warning(request,num):
    #num => 自転車番号
    target_histories = Borrow_history.objects.all().filter(bicycle_id = num)
    exceptionflag = False
    list = []
    my_nums = []
    if(Bicycle.objects.get(bicycle_id = num).status == False):
        exceptionflag = True
    if(exceptionflag == False):
        for item in target_histories:
            list.append(item.employee_id.employee_id)#その自転車を借りているユーザのIDのリスト
    target_bicycle = Bicycle.objects.get(bicycle_id=num)
    offices = Office.objects.all()
    if(request.method=='POST'):
        #異動元の事務所の自転車台数を1減らす
        from_office = Office.objects.get(office_id = target_bicycle.office_id.office_id)
        new_nums1 = from_office.bicycle_nums_office - 1
        Office.objects.filter(office_id = target_bicycle.office_id.office_id).update(bicycle_nums_office = new_nums1)
        #その自転車の貸し出し履歴を初期化する
        target_office_id=request.POST['office']
        target_histories.delete()
        Bicycle.objects.filter(bicycle_id = num).update(status=False)
        #異動先の事務所の自転車台数を1増やす
        dst_office = Office.objects.get(office_id = target_office_id)
        new_nums2 = dst_office.bicycle_nums_office + 1
        Office.objects.filter(office_id = dst_office.office_id).update(bicycle_nums_office = new_nums2)
        #新しい初期化された履歴を作る
        Bicycle.objects.filter(bicycle_id = num).update(office_id=target_office_id)
        new_borrow_history = Borrow_history(bicycle_id_id = num)
        new_borrow_history.save()
        if(exceptionflag == False):
            for target_id in list:
                Employee.objects.all().filter(employee_id = target_id).update(borrowed_bicycles = Employee.objects.get(employee_id = target_id).return_my_nums() - 1)
        return redirect(to='/admin_func/transfer_comp/' + str(num))
    params = {
        #'form':borrow_bicycleForm(),
        'data':target_histories,
        'target_bicycle':target_bicycle,
        'offices':offices,
        'num':num,
        }
    return render(request, 'admin_func/transfer_warning', params)

@login_required
def transfer_comp(request,num):
    #num 自転車番号
    bicycle = Bicycle.objects.get(bicycle_id=num)
    params = {
        'obj':bicycle,
        }
    return render(request, 'admin_func/transfer_comp', params)

templates/admin_func/top.html
<!doctype html>
<html lang="ja">

{% load static %}

<head>
	<link rel="stylesheet" type="text/css" href="{% static 'bicycle_borrow_sub_sys/style.css' %}">
	<mata charset="utf-8">
		<title>{{title}}</title>
</head>

<body>
	<header>
		<div class="header-logo">
			管理者用トップ画面 <span class="hello">こんにちは {{ user.username }} さん。</span>
		</div>
		<div class="header-list">
			<ul>
				<li><a href="{% url 'accounts:logout' %}" class="logout">ログアウト</a></li>
				<li><a href="{% url 'bicycle_borrow_sub_sys:top' %}" class="logout">一般社員画面に移動する</a></li>
			</ul>
		</div>
	</header>

	<div class="main">
		<div class="message">
			移動する自転車を選択してください。
		</div>

		<div class="accbox">
			<label for="office1">{{office1.office_name}} | 現在、{{office1.bicycle_nums_office}}台の自転車があります</label>
			<input type="checkbox" id="office1" class="cssacc" />
			<div class="accshow">
				<table>
					<tr>
					<th>貸出番号</th>
						<th>自転車番号</th>
						<th>色</th>
						<th>利用状況</th>
						<th>社員番号</th>
						<th>名前</th>
						<th>使用日数</th>
						<th></th>
					</tr>
					{% for item in data %} {% if item.bicycle_id.office_id.office_id == 1 %}
						<tr>
						<td>{{item.borrow_id}}</td>
						<td>{{item.bicycle_id.bicycle_id}}</td>
						<td>{% if item.bicycle_id.color == 0 %}ピンク{% endif %}{% if item.bicycle_id.color == 1 %}オレンジ{% endif %}{% if item.bicycle_id.color == 2 %}グリーン{% endif %}</td>
						{% if item.bicycle_id.status == False %}
						<td>未使用</td>
						<td> ー </td>
						<td> ー </td>
						<td> ー </td>
						{% endif %}
						{% if item.how_long_borrow >= 20 %}
							{% if item.bicycle_id.status == True %}
							<td>使用中</td>
							<td class="disp_red_warning">{{item.employee_id.employee_id}}</td>
							<td class="disp_red_warning">{{item.employee_id.username}}</td>
							<td class="disp_red_warning">{{item.how_long_borrow}}</td>
							{% endif %}
						{% elif item.how_long_borrow >= 10 %}
							{% if item.bicycle_id.status == True %}
							<td>使用中</td>
							<td class="disp_yellow_warning">{{item.employee_id.employee_id}}</td>
							<td class="disp_yellow_warning">{{item.employee_id.username}}</td>
							<td class="disp_yellow_warning">{{item.how_long_borrow}}</td>
							{% endif %}
			    		{% else %}
							{% if item.bicycle_id.status == True %}
							<td>使用中</td>
							<td>{{item.employee_id.employee_id}}</td>
							<td>{{item.employee_id.username}}</td>
							<td>{{item.how_long_borrow}}</td>
							{% endif %}
						{% endif %}
						<td><a href="{% url 'admin_func:transfer_warning' item.bicycle_id.bicycle_id %}">移動する</td>
						{% endif %} 
					{% endfor %}
				</table>
			</div>
			<label for="office2">{{office2.office_name}} | 現在、{{office2.bicycle_nums_office}}台の自転車があります</label>
			<input type="checkbox" id="office2" class="cssacc" />
			<div class="accshow">
				<table>
					<tr>
					<th>貸出番号</th>
						<th>自転車番号</th>
						<th>色</th>
						<th>利用状況</th>
						<th>社員番号</th>
						<th>名前</th>
						<th>使用日数</th>
						<th></th>
					</tr>
					{% for item in data %} {% if item.bicycle_id.office_id.office_id == 2 %}
						<tr>
						<td>{{item.borrow_id}}</td>
						<td>{{item.bicycle_id.bicycle_id}}</td>
						<td>{% if item.bicycle_id.color == 0 %}ピンク{% endif %}{% if item.bicycle_id.color == 1 %}オレンジ{% endif %}{% if item.bicycle_id.color == 2 %}グリーン{% endif %}</td>
						{% if item.bicycle_id.status == False %}
						<td>未使用</td>
						<td> ー </td>
						<td> ー </td>
						<td> ー </td>
						{% endif %}
						{% if item.how_long_borrow >= 20 %}
							{% if item.bicycle_id.status == True %}
							<td>使用中</td>
							<td class="disp_red_warning">{{item.employee_id.employee_id}}</td>
							<td class="disp_red_warning">{{item.employee_id.username}}</td>
							<td class="disp_red_warning">{{item.how_long_borrow}}</td>
							{% endif %}
						{% elif item.how_long_borrow >= 10 %}
							{% if item.bicycle_id.status == True %}
							<td>使用中</td>
							<td class="disp_yellow_warning">{{item.employee_id.employee_id}}</td>
							<td class="disp_yellow_warning">{{item.employee_id.username}}</td>
							<td class="disp_yellow_warning">{{item.how_long_borrow}}</td>
							{% endif %}
			    		{% else %}
							{% if item.bicycle_id.status == True %}
							<td>使用中</td>
							<td>{{item.employee_id.employee_id}}</td>
							<td>{{item.employee_id.username}}</td>
							<td>{{item.how_long_borrow}}</td>
							{% endif %}
						{% endif %}
						<td><a href="{% url 'admin_func:transfer_warning' item.bicycle_id.bicycle_id %}">移動する</td>
						{% endif %} 
					{% endfor %}
				</table>
			</div>
			<label for="office3">{{office3.office_name}} | 現在、{{office3.bicycle_nums_office}}台の自転車があります</label>
			<input type="checkbox" id="office3" class="cssacc" />
			<div class="accshow">
				<table>
					<tr>
					<th>貸出番号</th>
						<th>自転車番号</th>
						<th>色</th>
						<th>利用状況</th>
						<th>社員番号</th>
						<th>名前</th>
						<th>使用日数</th>
						<th></th>
					</tr>
					{% for item in data %} {% if item.bicycle_id.office_id.office_id == 3 %}
						<tr>
						<td>{{item.borrow_id}}</td>
						<td>{{item.bicycle_id.bicycle_id}}</td>
						<td>{% if item.bicycle_id.color == 0 %}ピンク{% endif %}{% if item.bicycle_id.color == 1 %}オレンジ{% endif %}{% if item.bicycle_id.color == 2 %}グリーン{% endif %}</td>
						{% if item.bicycle_id.status == False %}
						<td>未使用</td>
						<td> ー </td>
						<td> ー </td>
						<td> ー </td>
						{% endif %}
						{% if item.how_long_borrow >= 20 %}
							{% if item.bicycle_id.status == True %}
							<td>使用中</td>
							<td class="disp_red_warning">{{item.employee_id.employee_id}}</td>
							<td class="disp_red_warning">{{item.employee_id.username}}</td>
							<td class="disp_red_warning">{{item.how_long_borrow}}</td>
							{% endif %}
						{% elif item.how_long_borrow >= 10 %}
							{% if item.bicycle_id.status == True %}
							<td>使用中</td>
							<td class="disp_yellow_warning">{{item.employee_id.employee_id}}</td>
							<td class="disp_yellow_warning">{{item.employee_id.username}}</td>
							<td class="disp_yellow_warning">{{item.how_long_borrow}}</td>
							{% endif %}
			    		{% else %}
							{% if item.bicycle_id.status == True %}
							<td>使用中</td>
							<td>{{item.employee_id.employee_id}}</td>
							<td>{{item.employee_id.username}}</td>
							<td>{{item.how_long_borrow}}</td>
							{% endif %}
						{% endif %}
						<td><a href="{% url 'admin_func:transfer_warning' item.bicycle_id.bicycle_id %}">移動する</td>
						{% endif %} 
					{% endfor %}
				</table>
	 		</div>
		</div>
	</body>
</html>
	