Teilt_Fahrrad/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView



urlpatterns = [
    path('admin/', admin.site.urls),
    #    path('', RedirectView.as_view(url='/accounts/login/')),
    #path('accounts/', include('accounts.urls')),
    path('', RedirectView.as_view(url='/accounts/login/')),
    path('accounts/', include("accounts.urls")),
    path('admin_func/', include("admin_func.urls")),
    path('bicycle_borrow_sub_sys/', include('bicycle_borrow_sub_sys.urls')),
]

accounts/urls.py
'''
Created on 2018/12/12

@author: t16cs060
'''

from django.urls import path
from . import views
from django.urls.conf import include

app_name = 'accounts'

urlpatterns = [
    path('login/', views.employee_login, name='login'),
    path('logout/', views.employee_logout, name='logout'),
    path('manager_login/', views.manager_login, name='manager_login'),
    path('manager_logout/', views.manager_logout, name='manager_logout'),
    path('top_test/', views.top_test, name='top_test'),
    path('manager_top_test/', views.manager_top_test, name='manager_top_test')
]

bicycle_borrow_sub_sys/urls.py
from django.urls import path
from . import views
from django.urls.conf import include

app_name = 'bicycle_borrow_sub_sys'

urlpatterns = [
    path('', views.top, name='top'),
    path('borrow_bicycle/', views.borrow_bicycle, name='borrow_bicycle'),
    path('borrow_warning/<int:num>', views.borrow_warning, name='borrow_warning'),
    path('borrowed/<int:num>', views.borrowed, name='borrowed'),
    path('return_bicycle/', views.return_bicycle, name='return_bicycle'),
    path('return_warning/', views.return_warning, name='return_warning'),
    path('returned/<int:num>', views.returned, name='returned'),
    path('accounts/',include('accounts.urls'))
    ]

bicycle_borrow_sub_sys/models.py
from django.db import models
from accounts.models import Employee
import datetime
import time
from django.utils import timezone
from datetime import timedelta

# Create your models here.

class Office(models.Model):
    office_id = models.IntegerField(primary_key=True)
    office_name = models.CharField(max_length=6)
    bicycle_nums_office = models.IntegerField()
    
    
    
    
class Bicycle(models.Model):
    bicycle_id = models.IntegerField(primary_key = True)
    color = models.IntegerField()
    status = models.BooleanField()
    office_id = models.ForeignKey(Office,on_delete=models.SET_NULL,
    null=True)
    
    
    
class Borrow_history(models.Model):
    borrow_id = models.IntegerField(primary_key = True)
    bicycle_id = models.ForeignKey(Bicycle,on_delete=models.SET_NULL,
    null=True)
    employee_id = models.ForeignKey(Employee,on_delete=models.SET_NULL,
    null=True, blank=True)
    start_day = models.DateField(null=True,blank=True)
    
    def how_long_borrow(self):
        if(self.start_day == None):
            return -1
        now = datetime.date.today()
        return (now - self.start_day).days

bicycle_borrow_sub_sys/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Borrow_history
from django.shortcuts import redirect
from .models import Bicycle
from .models import Office
import datetime
from django.contrib.auth.decorators import login_required
import time
from .models import Employee
from django.urls import reverse
from django.contrib import messages

@login_required
def top(request):
    all_my_bike = Borrow_history.objects.all().filter(employee_id=request.user.employee_id).count()
    params = {
        'title':'トップ画面',
        'all_my_bike':all_my_bike
        }
    return render(request, 'bicycle_borrow_sub_sys/top.html', params)

@login_required
def borrow_bicycle(request):
    office2 = Office.objects.get(office_id=2)
    office1 = Office.objects.get(office_id=1)
    office3 = Office.objects.get(office_id=3)
    data = Borrow_history.objects.all().order_by('bicycle_id')
    nums1 = Bicycle.objects.all().filter(office_id=1).count()
    nums2 = Bicycle.objects.all().filter(office_id=2).count()
    nums3 = Bicycle.objects.all().filter(office_id=3).count()
    list = []
    already_borrow_bicycle = Borrow_history.objects.all().filter(employee_id=request.user.employee_id)
    for bike in already_borrow_bicycle:
        list.append(bike.bicycle_id)#Jibun ga karite iru jitensya no borrow_id no ichiran(list)
    params = {
        'title':'借りる画面',
        #'msg':'借りる自転車を選択してください',
        #'form':borrow_bicycleForm(),
        'data':data,
        'list':list,
        'nums1':nums1,
        'nums2':nums2,
        'nums3':nums3,
        'office1': office1,
        'office2': office2,
        'office3': office3,
        }
    return render(request, 'bicycle_borrow_sub_sys/borrow_bicycle.html', params)


def borrow_warning(request, num):
    bicycle_borrowed_history = Borrow_history.objects.all().filter(bicycle_id=num)
    #my_bicycles = request.user.borrowed_bicycles
    my_bicycles = Borrow_history.objects.all().filter(employee_id = request.user.employee_id).count()
    my_limit = 3 - my_bicycles
    bicycle = Bicycle.objects.get(bicycle_id=num)
    params = {
        'title':'貸し出し確認画面',
        'data':bicycle_borrowed_history,
        'obj':bicycle,
        'my_limit':my_limit,
        }

    if(request.method == 'POST'):
        #もし自転車を3台以上借りている場合
        if(my_bicycles>=3):
            messages.success(request, '自転車を3台借りています。これ以上借りることはできません。')
            #return redirect(request, 'bicycle_borrow_sub_sys/borrow_warning.html')
        #もし自転車を3台以上借りていない場合
        if(my_bicycles<3):
            #その自転車の履歴が何個あるか
            if(bicycle_borrowed_history.count() ==1):
                for bike in bicycle_borrowed_history:
                        #もしその自転車が誰にも借りられていない場合
                    if(bike.employee_id is None):
                        bicycle_borrowed_history.delete()
                        date = datetime.date.today()
                        b_history  = Borrow_history(bicycle_id_id = num ,  employee_id_id = request.user.employee_id, start_day = date)
                        b_history.save()
                        my_limit = my_limit - 1
                        Bicycle.objects.filter(bicycle_id = num).update(status=True)
                        my_bicycles = my_bicycles+1
                        Employee.objects.all().filter(employee_id = request.user.employee_id).update(borrowed_bicycles = my_bicycles)
                        return redirect(to='/bicycle_borrow_sub_sys/borrowed/' + str(num))
                    else:
                        #その自転車が誰かに（1人）借りられたいた場合
                        date = datetime.date.today()
                        b_history  = Borrow_history(bicycle_id_id = num ,  employee_id_id = request.user.employee_id, start_day = date)
                        b_history.save()
                        my_bicycles = my_bicycles+1
                        Employee.objects.all().filter(employee_id = request.user.employee_id).update(borrowed_bicycles = my_bicycles)
                        my_limit = my_limit - 1
                        return redirect(to='/bicycle_borrow_sub_sys/borrowed/' + str(num))
            else:
                #もしその自転車が誰かに（1人以上）借りられていた場合
                date = datetime.date.today()
                b_history  = Borrow_history(bicycle_id_id = num ,  employee_id_id = request.user.employee_id, start_day = date)
                b_history.save()
                my_bicycles = my_bicycles+1
                Employee.objects.all().filter(employee_id = request.user.employee_id).update(borrowed_bicycles = my_bicycles)
                my_limit = my_limit - 1
                return redirect(to='/bicycle_borrow_sub_sys/borrowed/' + str(num))
    
    return render(request, 'bicycle_borrow_sub_sys/borrow_warning.html', params)

@login_required
def borrowed(request, num):
    bicycle = Bicycle.objects.get(bicycle_id=num)
    all_my_bike = Borrow_history.objects.all().filter(employee_id=request.user.employee_id)
    rest_num_can_borrow = 3 - all_my_bike.count()
    params = {
        'title':'貸し出し完了画面',
        'obj':bicycle,
        'rest_num_can_borrow':rest_num_can_borrow
        }
    
    return render(request, 'bicycle_borrow_sub_sys/borrowed.html', params)

    

@login_required
def return_bicycle(request):
    data = Borrow_history.objects.all().filter(employee_id=request.user.employee_id)
    num = Borrow_history.objects.all().filter(employee_id=request.user.employee_id).count()
    data2=Office.objects.all()
    params = {
        'title':'返す画面',
        'msg':'返す自転車を選択してください',
        #'form':borrow_bicycleForm(),
        'data':data,
        'data2':data2,
        }
    if(num==0):
        params['title']="あなたは一台も借りていません"
        params['msg']="ログアウトまたはトップページへ戻ってください"
        
        return render(request, 'bicycle_borrow_sub_sys/return_bicycle_nobike.html', params)
    else:
        return render(request, 'bicycle_borrow_sub_sys/return_bicycle.html', params)


@login_required
def return_warning(request):
    params = {
        'title':'返却確認',
        'msg':'返却内容はこれでよいですか？',
        #'form':borrow_bicycleForm(),
        'data':[],
        'data2':[],
        }
    if(request.method=='POST'):
        oid=request.POST['office']
        bid=request.POST['bicycle']
        item2=Office.objects.get(office_id=oid)
        item=Bicycle.objects.get(bicycle_id=bid)
        params['data']=item
        params['data2']=item2
        return render(request, 'bicycle_borrow_sub_sys/return_warning.html', params)
    else:
        return HttpResponse("入力に不備がありました")

@login_required
def returned(request, num):
    data = Bicycle.objects.get(bicycle_id=num)
    all_my_bike = Borrow_history.objects.all().filter(employee_id=request.user.employee_id)
    rest_num_can_borrow =all_my_bike.count()
    my_limit=3 - rest_num_can_borrow
    rest_num_can_borrow = rest_num_can_borrow-1
    Employee.objects.all().filter(employee_id = request.user.employee_id).update(borrowed_bicycles = rest_num_can_borrow)
    my_limit = my_limit + 1
    params = {
        'title':'返却完了しました',
        'data':data,
        'my_limit':my_limit
        }
    if(request.method=='POST'):
        oid=request.POST['office']#返却先事務所
        bid=request.POST['bicycle']
        borrow_bike_num=Borrow_history.objects.all().filter(bicycle_id=bid).count()
        bike=Bicycle.objects.get(bicycle_id=bid)
        office_a=Office.objects.get(office_id=oid)
        office_b=Office.objects.get(office_id=bike.office_id.office_id)
        item=Borrow_history.objects.all().filter(employee_id=request.user.employee_id,bicycle_id=bid)
        item.delete()
        bike.office_id=office_a
        bike.save()
        if(office_a.office_id!=office_b.office_id):
        
            office_a.bicycle_nums_office+=1
            office_a.save()
            office_b.bicycle_nums_office-=1
            office_b.save()
        
        if(borrow_bike_num==1):
            bike.status = False
            bike.save()
            date = datetime.datetime.today()
            b_history = Borrow_history(bicycle_id_id = bid , start_day = date)
            b_history.save()
            
        return render(request, 'bicycle_borrow_sub_sys/returned.html', params)
        
    else:
        return HttpResponse("Hello NO Return Warning!")

templates/bicycle_borrow_sub_sys/borrow_bicycle.html
{% load static %}

<!doctype html>
<html>
	<head>
        <meta charset="utf-8">
        <title>{{ title }}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'bicycle_borrow_sub_sys/style.css' %}">
    </head>

	<body>
	<header>
			<div class="header-logo">
				借りる画面
				<span class="hello">こんにちは {{ user.username }} さん。</span>
			</div>
			<div class="header-list">
				<ul>
					<li><a href="{% url 'accounts:logout' %}" class="logout">ログアウト</a></li>
					<li><a href="{% url 'bicycle_borrow_sub_sys:top' %}" class="logout">トップに戻る</a></li>
				</ul>
			</div>
	</header>
	<div class="main">
		<div class="message">
			利用する自転車を選択してください。
		</div>
	
		<div class="accbox">
			<label for="office1">{{office1.office_name}} | 現在、{{office1.bicycle_nums_office}}台の自転車があります</label>
			<input type="checkbox" id="office1" class="cssacc" />
			<div class="accshow">
				<table>
					<tr>
					  <th>自転車番号</th>
					  <th>色</th>
					  <th>利用状況</th>
					  <th>社員番号</th>
					  <th>名前</th>
					  <th>使用日数</th>
					  <th></th>
					</tr>
			    	{% for item in data %}
						{% if item.bicycle_id.office_id.office_id == 1 %}
						    <tr>
						    <td>{{item.bicycle_id.bicycle_id}}</td>
						    <td>{% if item.bicycle_id.color == 0 %}ピンク{% endif %}{% if item.bicycle_id.color == 1 %}オレンジ{% endif %}{% if item.bicycle_id.color == 2 %}グリーン{% endif %}</td>
						    {% if item.bicycle_id.status == False %}
						    	<td>未使用</td>
						    	<td> ー </td>
						    	<td> ー </td>
							   	<td> ー </td>
							{% endif %}
						    {% if item.bicycle_id.status == True %}
						    	<td>使用中</td>
						    	<td>{{item.employee_id.employee_id}}</td>
						    	<td>{{item.employee_id.username}}</td>
						   	 	<td>{{item.how_long_borrow}}</td>
							{% endif %}
						    <td>{% if item.bicycle_id in list %}既に借りています{% endif %}{% if item.bicycle_id not in list %}<a href="{% url 'bicycle_borrow_sub_sys:borrow_warning' item.bicycle_id.bicycle_id %}">利用する</a>{% endif %}</td>
						{% endif %}
					{% endfor %}
		 		</table>
	 		</div>
		 	<label for="office2">{{office2.office_name}} | 現在、{{office2.bicycle_nums_office}}台の自転車があります</label>
			<input type="checkbox" id="office2" class="cssacc" />
			<div class="accshow">
				<table>
					<tr>
					  <th>自転車番号</th>
					  <th>色</th>
					  <th>利用状況</th>
					  <th>社員番号</th>
					  <th>名前</th>
					  <th>使用日数</th>
					  <th></th>
					</tr>
			    	{% for item in data %}
						{% if item.bicycle_id.office_id.office_id == 2 %}
						    <tr>
						    <td>{{item.bicycle_id.bicycle_id}}</td>
						    <td>{% if item.bicycle_id.color == 0 %}ピンク{% endif %}{% if item.bicycle_id.color == 1 %}オレンジ{% endif %}{% if item.bicycle_id.color == 2 %}グリーン{% endif %}</td>
						    {% if item.bicycle_id.status == False %}
						    	<td>未使用</td>
						    	<td> ー </td>
						    	<td> ー </td>
							   	<td> ー </td>
							{% endif %}
						    {% if item.bicycle_id.status == True %}
						    	<td>使用中</td>
						    	<td>{{item.employee_id.employee_id}}</td>
						    	<td>{{item.employee_id.username}}</td>
						   	 	<td>{{item.how_long_borrow}}</td>
							{% endif %}
						    <td>{% if item.bicycle_id in list %}既に借りています{% endif %}{% if item.bicycle_id not in list %}<a href="{% url 'bicycle_borrow_sub_sys:borrow_warning' item.bicycle_id.bicycle_id %}">利用する</a>{% endif %}</td>
						{% endif %}
					{% endfor %}
		 		</table>
	 		</div>
	 		<label for="office3">{{office3.office_name}} | 現在、{{office3.bicycle_nums_office}}台の自転車があります</label>
			<input type="checkbox" id="office3" class="cssacc" />
			<div class="accshow">
				<table>
					<tr>
					  <th>自転車番号</th>
					  <th>色</th>
					  <th>利用状況</th>
					  <th>社員番号</th>
					  <th>名前</th>
					  <th>使用日数</th>
					  <th></th>
					</tr>
			    	{% for item in data %}
						{% if item.bicycle_id.office_id.office_id == 3 %}
						    <tr>
						    <td>{{item.bicycle_id.bicycle_id}}</td>
						    <td>{% if item.bicycle_id.color == 0 %}ピンク{% endif %}{% if item.bicycle_id.color == 1 %}オレンジ{% endif %}{% if item.bicycle_id.color == 2 %}グリーン{% endif %}</td>
						    {% if item.bicycle_id.status == False %}
						    	<td>未使用</td>
						    	<td> ー </td>
						    	<td> ー </td>
							   	<td> ー </td>
							{% endif %}
						    {% if item.bicycle_id.status == True %}
						    	<td>使用中</td>
						    	<td>{{item.employee_id.employee_id}}</td>
						    	<td>{{item.employee_id.username}}</td>
						   	 	<td>{{item.how_long_borrow}}</td>
							{% endif %}
						    <td>{% if item.bicycle_id in list %}既に借りています{% endif %}{% if item.bicycle_id not in list %}<a href="{% url 'bicycle_borrow_sub_sys:borrow_warning' item.bicycle_id.bicycle_id %}">利用する</a>{% endif %}</td>
						{% endif %}
					{% endfor %}
		 		</table>
	 		</div>
		</div>
	</body>
</html>

templates/bicycle_borrow_sub_sys/borrow_warning.html
<!doctype html>
<html lang="ja">

{% load static %}
<head>
        <meta charset="utf-8">
        <title>{{ title }}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'bicycle_borrow_sub_sys/style.css' %}">
</head>

<body>
	<header>
			<div class="header-logo">
				借りる画面
				<span class="hello">こんにちは {{ user.username }} さん。</span>
			</div>
			<div class="header-list">
				<ul>
					<li><a href="{% url 'accounts:logout' %}" class="logout">ログアウト</a></li>
					<li><a href="{% url 'bicycle_borrow_sub_sys:borrow_bicycle' %}" class="logout">戻る</a></li>
					<li><a href="{% url 'bicycle_borrow_sub_sys:top' %}" class="logout">トップに戻る</a></li>
				</ul>
			</div>
	</header>
	<div class="main">
		<div class="message">
			この自転車を利用しますか？
		</div>
		<table>
			<tr>
				<td bgcolor=#C0C0C0>事務所名</td>
				<td bgcolor=#808080>自転車番号</td>
				<td bgcolor=#00FFFF>自転車の色</td>
			</tr>
			<tr>
				<td bgcolor=#C0C0C0>{{obj.office_id.office_name}}</td>
				<td bgcolor=#808080>{{obj.bicycle_id}}</td>
				<td bgcolor=#00FFFF>{% if obj.color == 0 %}ピンク{% endif %}{% if obj.color == 1 %}オレンジ{% endif %}{% if obj.color == 2 %}グリーン{% endif %}</td>
			</tr>
		</table>
		<form action="{% url 'bicycle_borrow_sub_sys:borrow_warning' obj.bicycle_id %}" method="post">
			{% csrf_token %}<input type="submit" value="利用する">
		</form>
	</div>
</body>
</html>

templates/bicycle_borrow_sub_sys/borrowed.html
<!doctype html>
<html lang="ja">

{% load static %}
<head>
        <meta charset="utf-8">
        <title>{{ title }}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'bicycle_borrow_sub_sys/style.css' %}">
</head>
<body>
	<header>
			<div class="header-logo">
				借りる画面
				<span class="hello">こんにちは {{ user.username }} さん。</span>
			</div>
			<div class="header-list">
				<ul>
					<li><a href="{% url 'accounts:logout' %}" class="logout">ログアウト</a></li>
					<li><a href="{% url 'bicycle_borrow_sub_sys:top' %}" class="logout">一般社員トップ画面に戻る</a></li>
				</ul>
			</div>
	</header>
	<div class="main">
		<meta http-equiv="refresh" content='3;URL={% url 'bicycle_borrow_sub_sys:top' %}'>
		<div class="message">
			{{request.user.username}}さんによる自転車の貸出が完了しました。
			</br>
			借りられる台数は残り{{rest_num_can_borrow}}台です。
		</div>
		<table>
			<tr>
			<td>事務所名</td>
			<td>自転車番号</td>
			<td>自転車の色</td>
			</tr>
			<tr>
			<td>{{obj.office_id.office_name}}</td>
			<td>{{obj.bicycle_id}}</td>
			<td>{% if obj.color == 0 %}ピンク{% endif %}{% if obj.color == 1 %}オレンジ{% endif %}{% if obj.color == 2 %}グリーン{% endif %}</td>
			</tr>
		</table>
	<font size=5><p>3秒後に一般社員用画面トップに自動でジャンプします</p></font>
	</div>
</body>
</html>

templates/bicycle_borrow_sub_sys/return_bicycle.html
<!doctype html>
<html lang="ja">

{% load static %}
<head>
        <meta charset="utf-8">
        <title>{{ title }}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'bicycle_borrow_sub_sys/style.css' %}">
</head>

<body>
	<header>
			<div class="header-logo">
				返す画面
				<span class="hello">こんにちは {{ user.username }} さん。</span>
			</div>
			<div class="header-list">
				<ul>
					<li><a href="{% url 'accounts:logout' %}" class="logout">ログアウト</a></li>
					<li><a href="{% url 'bicycle_borrow_sub_sys:top' %}" class="logout">一般社員トップ画面に戻る</a></li>
				</ul>
			</div>
	</header>
	<div class="main">
		<div class="message">
			返却する自転車を選択してください。
		</div>
		  <form action="{% url 'bicycle_borrow_sub_sys:return_warning'  %}" method="post">{% csrf_token %}
		  <table>
		    <tr>
		      <!--  <th>borrow_id</th> -->
		      <th>自転車番号</th>
		      <th>色</th>
		      <th>利用状況</th>
		      <th>社員番号</th>
		      <th>名前</th>
		      <th>使用日数</th>
		      <th></th>
		    </tr>

		    {% for item in data %}
		    <tr>
		    <!--  <td>{{item.borrow_id}}</td> -->
		    <td>{{item.bicycle_id.bicycle_id}}</td>
		    <td>{% if item.bicycle_id.color == 0 %}ピンク{% endif %}{% if item.bicycle_id.color == 1 %}オレンジ{% endif %}{% if item.bicycle_id.color == 2 %}グリーン{% endif %}</td>
		    <td>使用中</td>
		    <td>{{item.employee_id.employee_id}}</td>
		    <td>{{item.employee_id.username}}</td>
		    <td>{{item.how_long_borrow}}</td>
		    <td><input type="radio" name="bicycle" value={{item.bicycle_id.bicycle_id}} required="required"></td>
		    </tr>
		    {%endfor %}
		   </table>
		   <table>
		   <tr>
		   <tr>返却先を選択してください。</tr>
		   </br>
		   <th>事務所名</th>
		   <th></th>
		   </tr>
		   {% for item in data2 %}
		   <tr>
		   <td>{{item.office_name}}</td>
		   <td><input type="radio" name="office" value={{item.office_id}} required="required"></td>
		   </tr>
		   {%endfor %}
		   </table>
		   <p>
		   <input type="submit" value="送信">
		   </p>
		   </form>
		</div>
	</body>
</html>

templates/bicycle_borrow_sub_sys/return_bicycle_nobike.html
<!doctype html>
<html lang="ja">

{% load static %}
<head>
  <link rel="stylesheet" type="text/css" href="{% static 'hello/style.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'hello/home.css' %}">
  <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
  <mata charset="utf-8">
    <title>{{title}}</title>
    <p style="text-align: right"><a href="{% url 'accounts:logout' %}">ログアウト</a> <a href="{% url 'bicycle_borrow_sub_sys:top' %}">top画面へ戻る</a></p>
</head>

<body>
  <span class="title_font"><h1>{{title}}</h1></span>
  <p>Hi {{ user.username }}</p>
  <p>{{msg}}</p>
  
 

templates/bicycle_borrow_sub_sys/return_warning.html
<!doctype html>
<html lang="ja">

{% load static %}
<head>
        <meta charset="utf-8">
        <title>{{ title }}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'bicycle_borrow_sub_sys/style.css' %}">
</head>

<body>
	<header>
			<div class="header-logo">
				返す画面
				<span class="hello">こんにちは {{ user.username }} さん。</span>
			</div>
			<div class="header-list">
				<ul>
					<li><a href="{% url 'accounts:logout' %}" class="logout">ログアウト</a></li>
					<li><a href="{% url 'bicycle_borrow_sub_sys:return_bicycle' %}" class="logout">戻る</a></li>
					<li><a href="{% url 'bicycle_borrow_sub_sys:top' %}" class="logout">トップに戻る</a></li>
				</ul>
			</div>
	</header>
	<div class="main">
		<div class="message">
			この自転車を返却しますか。
		</div>
		  
		  <table>
		    <tr>
		      <th>返却先</th>
		      <th>元事務所</th>
		      <th>自転車番号</th>
		      <th>自転車の色</th>
		      <th></th>
		    </tr>
		
		
		    <tr>
		     <td>{{data2.office_name}}</td>
		     <td>{{data.office_id.office_name}}</td>
		     <td>{{data.bicycle_id}}</td>
		     <td>{% if data.color == 0 %}ピンク{% endif %}{% if data.color == 1 %}オレンジ{% endif %}{% if data.color == 2 %}グリーン{% endif %}</td>
		    </tr>
		    
		   </table>
		   
		   <form action="{% url 'bicycle_borrow_sub_sys:returned' data.bicycle_id %}" method="post" ">{% csrf_token %}
		   <p>
		   <input type="hidden" name="bicycle" value="{{data.bicycle_id}}">
		   <input type="hidden" name="office" value="{{data2.office_id}}">
		   <input type="submit" value="返却する">
		   </p>
	</div>
</body>
</html>

templates/bicycle_borrow_sub_sys/top.html
{% load static %}

<doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{{ title }}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'bicycle_borrow_sub_sys/style.css' %}">
    </head>
	<body>	
		<header>
			<div class="header-logo">
				トップ画面
				<span class="hello">こんにちは {{ user.username }} さん。</span>
			</div>
			<div class="header-list">
				<ul>
					<li><a href="{% url 'accounts:logout' %}">
						ログアウト
					</a></li>
				</ul>
			</div>
		</header>
		<div class="main">
			<div class="message">
			<div class="now_bicycle">
				{% if all_my_bike == 0 %}
					現在、自転車を一台も借りていません。
				{% else %}
					現在、自転車を {{ all_my_bike }} 台借りています。
				{% endif %}
				{% if all_my_bike == 3 %}
					<div class="warning_to_borrow">
						これ以上借りることができません。返却処理を行ってください。
					</div>
				{% endif %}
			</div>
			</div>
			<div class="circle">
	       	{% if all_my_bike == 3 %}
		        	 <a href="{% url 'bicycle_borrow_sub_sys:return_bicycle' %}" class="return_circle" title="Return">返す</a>
				{% endif %}
				{% if all_my_bike == 0 %}
			       	<a href="{% url 'bicycle_borrow_sub_sys:borrow_bicycle' %}" class="borrow_circle" title="Borrow">借りる</a>   
			        
				{% endif %}
				{% if all_my_bike == 1 or all_my_bike == 2 %}
					<a href="{% url 'bicycle_borrow_sub_sys:borrow_bicycle' %}" class="borrow_circle" title="Borrow">借りる</a>   
		        	<a href="{% url 'bicycle_borrow_sub_sys:return_bicycle' %}" class="return_circle" title="Return">返す</a>
				{% endif %}
				</a>
			</div>
		</body>
</html>